In [1]:
import numpy as np

In [2]:
a = np.arange(10)
print(a)
print(a.dtype)

[0 1 2 3 4 5 6 7 8 9]
int32


In [3]:
b = np.array([1,2,3,4,],dtype = 'int8')
print(b)
print(b.dtype)

[1 2 3 4]
int8


In [4]:
c = np.array([1,2,3,4,5,],dtype = 'float16')
print(c)
print(c.dtype)

[1. 2. 3. 4. 5.]
float16


In [6]:
class people:
    def __init__(self,name,age):
        self.name = name
        self.age = age
d = np.array([people("王",18),people("李",20)])
print(d)
print(d.dtype)

object


In [8]:
f = np.array(['a','b'],dtype = 'S')
print(f)
print(f.dtype)
#关于bytes与str的转化解释，见链接→→ https://www.cnblogs.com/chownjy/p/6625299.html

[b'a' b'b']
|S1


In [9]:
e = np.array(['a','c'],dtype = 'U')
print(e)
print(e.dtype)

['a' 'c']
<U1


### 类型转化astype

In [12]:
uf = f.astype("U")
print(uf)
print(uf.dtype)
print(f.dtype)

['a' 'b']
<U1
|S1


为什么Numpy的数组中有这么多的数据类型？

1.Numpy底层代码由C语言编写
2.Numpy考虑到处理海量数据的性能，针对不同的数据给不同的类型，来节省内存空间