In [1]:
import numpy as np

ndarray.ndim分析数组的维度

In [13]:
a1 = np.array([1,2,3])
print(a1.ndim)
a2 = np.array([[1,2,3],[4,5,6]])
print(a2.ndim)
a3 = np.array([
    [
        [1,2,3]
    ],
    [
        [4,5,6]
    ]
])
print(a3.ndim)
a4 = np.array([
    [
        [
            [1,2,3]
        ],
        [
            [4,5,6]
        ]
    ]
])
print(a4.ndim)

1
2
3
4


ndarray.shape

In [14]:
print(a1.shape)
print(a2.shape)
print(a3.shape)#两块一行三个元素

(3,)
(2, 3)
(2, 1, 3)


ndarray.reshape修改数组的形状

In [17]:
a5 = a3.reshape((2,3))
print(a5)
print(a5.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [19]:
a6 = a3.reshape((6,))
print(a6)
print(a6.shape)

[1 2 3 4 5 6]
(6,)


ndarray.flatten扁平化

In [22]:
a7 = a3.flatten()
print(a7)

[1 2 3 4 5 6]


ndarray.size获取元素个数

In [25]:
count = a3.size
print(count)

6


ndarray.itemsize每一个元素所占用内存大小，单位是字节

In [29]:
itemsize = a3.itemsize
print(itemsize)
print(a3.dtype)
print(itemsize * a3.size)

4
int32
24
