In [1]:
import numpy as np

一维数组的索引切片

In [2]:
a1 = np.arange(10)
#进行索引操作
print(a1)
print(a1[6])
#进行切片操作
print(a1[4:6])
print(a1[0:9])
#使用步长
print(a1[::2])
print(a1[::3])
#使用负数来作为索引
print(a1[-1])
print(a1[-10])

[0 1 2 3 4 5 6 7 8 9]
6
[4 5]
[0 1 2 3 4 5 6 7 8]
[0 2 4 6 8]
[0 3 6 9]
9
0


多维数组

同一维数组用中括号[]来进行索引和切片，在中括号中，使用逗号进行分割，逗号前面是行，后面是列。

如果多维数组中有只有一个值，那么这个值就是行

In [3]:
b2 = np.random.randint(0,10,size=(4,6))
print(b2)

[[5 4 7 5 1 9]
 [1 8 2 5 3 9]
 [2 8 8 9 1 6]
 [5 0 7 1 6 8]]


In [4]:
x = b2[1:3]
print(x)
print(b2[[0,3]])#单独提取需要的行

[[1 8 2 5 3 9]
 [2 8 8 9 1 6]]
[[5 4 7 5 1 9]
 [5 0 7 1 6 8]]


In [5]:
print(b2[2,1])
print(b2[[2,3],[4,0]])#切记，[[x1,y1],[x2,y2]]其中x1对应x2，提取数值的理想格式为[x1,x2]

8
[1 5]


In [6]:
print(b2[1:3,2:4])#切记左开右闭
print(b2[:,1])

[[2 5]
 [8 9]]
[4 8 8 0]


#尤其注意[1:3,2:4]与[[2,3],[4,0]]的根本区别在于提取区域的连不连续

### 布尔索引

In [8]:
c2 = np.arange(24).reshape((4,6))
print(c2)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [12]:
print(c2 < 10)

[[ True  True  True  True  True  True]
 [ True  True  True  True False False]
 [False False False False False False]
 [False False False False False False]]


In [14]:
print(c2[c2<10])

[0 1 2 3 4 5 6 7 8 9]


In [17]:
print(c2[(c2 < 5) | (c2 > 10)])

[ 0  1  2  3  4 11 12 13 14 15 16 17 18 19 20 21 22 23]


布尔索引是通过相同数组上的True或Fasle来进行提取。提取的条件可以有多个，当有多个条件时，用|表示或，用&表示且。多条件时，每个条件必须同圆括号括起来。

### 值的替换

In [21]:
a3 = np.random.randint(0,10,size=(3,5))
print(a3)

[[7 6 2 4 1]
 [1 3 3 3 7]
 [8 7 9 3 1]]


In [23]:
#使用索引或切片来替换
a3[1] = 0
print(a3)

[[7 6 2 4 1]
 [0 0 0 0 0]
 [8 7 9 3 1]]


In [25]:
#使用条件索引来替换
a3[a3 < 3] = 1
print(a3)

[[7 6 1 4 1]
 [1 1 1 1 1]
 [8 7 9 3 1]]


In [28]:
#使用where函数来替换
result = np.where(a3 < 5,0,1)
print(result)

[[1 1 0 0 0]
 [0 0 0 0 0]
 [1 1 1 0 0]]
