In [1]:
import numpy as np

In [2]:
a1 = np.random.randint(0,5,size = (3,5))
print(a1)

[[0 4 2 0 3]
 [3 4 0 1 1]
 [4 2 2 2 0]]


In [3]:
print(a1 * 2)

[[0 8 4 0 6]
 [6 8 0 2 2]
 [8 4 4 4 0]]


In [4]:
a2 = np.random.randint(0,5,size = (3,5))
print(a2)

[[2 0 4 2 4]
 [3 1 4 1 1]
 [4 3 2 2 4]]


In [5]:
print(a1 + a2)

[[2 4 6 2 7]
 [6 5 4 2 2]
 [8 5 4 4 4]]


In [6]:
a3 = np.random.randint(0,5,size = (3,4))
print(a3)

[[2 0 4 1]
 [4 2 2 4]
 [2 0 3 4]]


In [7]:
a4 = np.random.randint(0,5,size = (3,1))
print(a4)
print("-"*30)
print(a1)

[[4]
 [2]
 [4]]
------------------------------
[[0 4 2 0 3]
 [3 4 0 1 1]
 [4 2 2 2 0]]


In [9]:
a1 + a4

array([[4, 8, 6, 4, 7],
       [5, 6, 2, 3, 3],
       [8, 6, 6, 6, 4]])

In [10]:
a5 = np.random.randint(0,5,size = (1,5))
print(a1)
print('-' * 30)
print(a5)

[[0 4 2 0 3]
 [3 4 0 1 1]
 [4 2 2 2 0]]
------------------------------
[[4 1 0 2 2]]


In [11]:
a1 + a5

array([[4, 5, 2, 2, 5],
       [7, 5, 0, 3, 3],
       [8, 3, 2, 4, 2]])

In [14]:
a6 = np.random.randint(0,5,size = (3,8,2))
a7 = np.random.randint(0,5,size = (8,1))
print(a6)
print("-" * 30)
print(a7)
print('-' * 30)
print(a6 + a7)

[[[0 4]
  [3 4]
  [1 3]
  [1 3]
  [3 3]
  [2 1]
  [4 4]
  [3 0]]

 [[2 4]
  [4 4]
  [0 4]
  [2 3]
  [0 1]
  [4 0]
  [2 3]
  [0 4]]

 [[2 0]
  [3 2]
  [1 4]
  [1 2]
  [4 2]
  [1 3]
  [4 2]
  [0 1]]]
------------------------------
[[3]
 [0]
 [0]
 [4]
 [1]
 [0]
 [0]
 [4]]
------------------------------
[[[3 7]
  [3 4]
  [1 3]
  [5 7]
  [4 4]
  [2 1]
  [4 4]
  [7 4]]

 [[5 7]
  [4 4]
  [0 4]
  [6 7]
  [1 2]
  [4 0]
  [2 3]
  [4 8]]

 [[5 3]
  [3 2]
  [1 4]
  [5 6]
  [5 3]
  [1 3]
  [4 2]
  [4 5]]]


## 总结
1.数组和数字直接进行运算是没问题的

2.两个shape相同的数组可以进行运算

3.如果两个shape不相同的数组，想要进行运算，那么需要看他们是否满足广播原则

广播原则：如果两个数组的后缘维度(从末尾开始算起的维度)的轴长度相符或其中一方的长度为1，则仍未他们是广播兼容的。广播会在缺失和(或)长度为1的维度上进行