In [1]:
import numpy as np

In [2]:
a1 = np.random.randint(0,10,size = (3,4))
print(a1)

[[5 1 3 5]
 [5 6 8 6]
 [1 9 9 9]]


In [3]:
print(a1.reshape(2,6))
print(a1)

[[5 1 3 5 5 6]
 [8 6 1 9 9 9]]
[[5 1 3 5]
 [5 6 8 6]
 [1 9 9 9]]


In [4]:
a1.resize((4,3))
print(a1)

[[5 1 3]
 [5 5 6]
 [8 6 1]
 [9 9 9]]


#### reshape和resize都可以重新定义形状，但reshape不会修改数组本身，而是将修改后的结果返回回去。resize是直接修改数组本身。

### flatten和ravel函数

In [5]:
a2 = np.random.randint(0,10,size = (3,4))
print(a2)

[[0 6 4 4]
 [4 5 6 7]
 [9 0 2 9]]


In [6]:
a3 = a2.flatten()
a3[0] = 100
print(a2[0,0])

0


In [7]:
a4 = a2.ravel()
a4[0] = 100
print(a2[0,0])

100


#### 总结，两个函数都可将数组扁平化。但在通过索引修改数组元素时，ravel会直接改变原数组的值，而flatten则不影响

## 不同数组的组合

In [8]:
v1 = np.random.randint(0,10,size = (3,4))
print(v1)
print('-' * 15)
v2 = np.random.randint(0,10,size = (1,4))
print(v2)
print('-' * 15)
v3 = np.vstack([v1,v2])
print(v3)

[[4 5 4 0]
 [4 2 7 7]
 [2 6 5 6]]
---------------
[[0 2 4 4]]
---------------
[[4 5 4 0]
 [4 2 7 7]
 [2 6 5 6]
 [0 2 4 4]]


In [9]:
h1 = np.random.randint(0,10,size = (3,4))
print(h1)
print('-' * 15)
h2 = np.random.randint(0,10,size = (3,6))
print(h2)
print('-' * 25)
h3 = np.hstack([h1,h2])
print(h3)

[[3 3 3 8]
 [7 4 5 2]
 [0 2 3 2]]
---------------
[[4 1 4 0 2 8]
 [4 5 9 3 9 8]
 [8 8 2 6 5 4]]
-------------------------
[[3 3 3 8 4 1 4 0 2 8]
 [7 4 5 2 4 5 9 3 9 8]
 [0 2 3 2 8 8 2 6 5 4]]


In [10]:
c1 = np.random.randint(0,10,size = (3,4))
print(c1)
print('-' * 15)
c2 = np.random.randint(0,10,size = (3,6))
print(c2)
print('-' * 25)
c3 = np.concatenate([c1,c2],axis = 1)#axis = 1 是列拼接 = 0 是行拼接
print(c3)
print('-' * 25)
c4 = c1.reshape(2,6)
print(c4)
print('-' * 15)
c5 = np.concatenate([c2,c4],axis = 0)
print(c5)

[[5 5 5 7]
 [3 9 2 5]
 [9 1 2 2]]
---------------
[[7 6 5 6 4 2]
 [5 1 7 3 3 3]
 [7 0 0 8 3 8]]
-------------------------
[[5 5 5 7 7 6 5 6 4 2]
 [3 9 2 5 5 1 7 3 3 3]
 [9 1 2 2 7 0 0 8 3 8]]
-------------------------
[[5 5 5 7 3 9]
 [2 5 9 1 2 2]]
---------------
[[7 6 5 6 4 2]
 [5 1 7 3 3 3]
 [7 0 0 8 3 8]
 [5 5 5 7 3 9]
 [2 5 9 1 2 2]]


In [11]:
c6 = np.concatenate([c2,c4],axis = None)
print(c6)

[7 6 5 6 4 2 5 1 7 3 3 3 7 0 0 8 3 8 5 5 5 7 3 9 2 5 9 1 2 2]


#### 总计：vstack是行叠加，hstack是列叠加，concatenate可以行或列叠加(axis)，若axis = None，会先进行叠加，再转化为一维数组

In [12]:
hs1 = np.random.randint(0,10,size = (3,4))
print(hs1)
print('-' * 30)
hs2 = np.hsplit(hs1, 2)#平均分割
print(hs2)
print('-' * 30)
hs3 = np.hsplit(hs1, (1,2))#不规则切割
print(hs3)

[[1 4 4 5]
 [3 2 8 2]
 [6 1 2 0]]
------------------------------
[array([[1, 4],
       [3, 2],
       [6, 1]]), array([[4, 5],
       [8, 2],
       [2, 0]])]
------------------------------
[array([[1],
       [3],
       [6]]), array([[4],
       [2],
       [1]]), array([[4, 5],
       [8, 2],
       [2, 0]])]


In [13]:
vs1 = np.random.randint(0,10,size = (5,5))
print(vs1)
vs2 = np.vsplit(vs1,5)
print('-' * 30)
print(vs2)
vs3 = np.vsplit(vs1,(2,3))
print('-' * 30)
vs3

[[0 0 3 2 8]
 [7 0 8 5 0]
 [1 7 1 6 2]
 [4 8 4 0 5]
 [1 0 0 5 8]]
------------------------------
[array([[0, 0, 3, 2, 8]]), array([[7, 0, 8, 5, 0]]), array([[1, 7, 1, 6, 2]]), array([[4, 8, 4, 0, 5]]), array([[1, 0, 0, 5, 8]])]
------------------------------


[array([[0, 0, 3, 2, 8],
        [7, 0, 8, 5, 0]]),
 array([[1, 7, 1, 6, 2]]),
 array([[4, 8, 4, 0, 5],
        [1, 0, 0, 5, 8]])]

In [14]:
np.split(vs1,(2,3),axis = 0)#axis = 1 是列切割 = 0 是行切割

[array([[0, 0, 3, 2, 8],
        [7, 0, 8, 5, 0]]),
 array([[1, 7, 1, 6, 2]]),
 array([[4, 8, 4, 0, 5],
        [1, 0, 0, 5, 8]])]

#### 总结：hsplit是列切割，vsplit是行切割，split可以进行行或列切割。切割既可以平均切割也可以不规则切割。

### 矩阵的转置和轴对换

In [15]:
t1 = np.random.randint(0,10,size = (3,4))
print(t1)

[[3 0 4 3]
 [4 9 8 5]
 [1 8 2 8]]


In [20]:
print(t1.T)
print('-' * 20)
print(t1.dot(t1.T))

[[3 4 1]
 [0 9 8]
 [4 8 2]
 [3 5 8]]
--------------------
[[ 34  59  35]
 [ 59 186 132]
 [ 35 132 133]]


In [23]:
print(t1.transpose())
t2 = t1.transpose()#是一个view
t2[0] = 100
print(t1)
print(t2)

[[3 4 1]
 [0 9 8]
 [4 8 2]
 [3 5 8]]
[[100   0   4   3]
 [100   9   8   5]
 [100   8   2   8]]
[[100 100 100]
 [  0   9   8]
 [  4   8   2]
 [  3   5   8]]
